language: node_js
node_js:
- '7'
install:
  # Install any dependencies required for building your site here.
  # `awscli` is required for invalidation of CloudFront distributions and sync file to s# bucket
  - pip install --user awscli
before_install:
  - npm install
script:
  - npm run build
deploy:
  # Control deployment by setting a value for `on`. Setting the `branch`
  # option to `master` means Travis will only attempt a deployment on
  # builds of your repo's master branch (e.g., after you merge a PR).
  on:
    branch: master

  # s3 sync of build folder, with delete of inexisting file 
  # Environmenet variable are expecting to be set for aws to run :
  # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION
  provider: script
  script: 
    - aws s3 sync build s3://gfg.pricing-engine.uat --delete
  skip_cleanup: true

  # s3 travis deploment plugins, but no --delete sync
  # provider: s3
  # # You can refer to environment variables from Travis repo settings!
  # access_key_id: $AWS_ACCESS_KEY_ID
  # secret_access_key: $AWS_SECRET_ACCESS_KEY
  # region: ap-southeast-1
  # # Name of the S3 bucket to which your site should be uploaded.
  # bucket: gfg.pricing-engine.uat
  # # Prevent Travis from deleting your built site so it can be uploaded.
  # skip_cleanup: true
  # # Path to a directory containing your built site.
  # local_dir: build
  # # Set the Cache-Control header.
  # cache_control: "max-age=21600"