language: node_js
node_js:
- '7'
install:
  # Install any dependencies required for building your site here.
  # `awscli` is required for invalidation of CloudFront distributions and sync file to s# bucket
  - pip install --user awscli
before_install:
  - npm install
script:
  - npm run build
branches:
  except:
    - /^build-[0-9a-z\-]*/

deploy:
  # Control deployment by setting a value for `on`. Setting the `branch`
  # option to `develop` means Travis will only attempt a deployment on
  # builds of your repo's develop branch (e.g., after you merge a PR).
  on:
    branch: develop

  # s3 sync of build folder, with delete of inexisting file 
  # Environmenet variable are expecting to be set for aws to run :
  # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION
  provider: script
  script: 
    - aws s3 sync build s3://gfg.pricing-engine.uat --delete
  skip_cleanup: true

# after_success:
#   - git config credential.helper "store --file=.git/credentials" 
#   - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
#   - git config --global user.email "builds@travis-ci.com"
#   - git config --global user.name "Travis CI"
#   - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
#   - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
#   - git push origin $GIT_TAG
